I refactored the issue and renamed it IssueTicket to give it a clear objective  and Descriptive Name
hnicolus/CodeClinic pull request #7
Opened 2020-11-16 03:26 UTC by hnicolus

I refactored the issue modal and renamed it Issue Ticket to give it a clear objective and also refactored classes depending on on Issue

`public class Issue
{
  ....
}`

to 
`public class IssueTicket
{
  ....
}`

2020-11-16 07:33 UTC, PhutiCee requested changes

2020-11-16 07:33 UTC, PhutiCee commented on src/Application/IssueTickets/Commands/CreateIssueTicket/CreateIssueCommandValidator.cs
> -    public class CreateIssueCommandValidator : AbstractValidator<CreateIssueCommand>
It should be `<CreateIssueTicketCommand>`, I think

2020-11-16 07:42 UTC, nicksoftware commented on src/Application/IssueTickets/Commands/CreateIssueTicket/CreateIssueCommandValidator.cs
> -    public class CreateIssueCommandValidator : AbstractValidator<CreateIssueCommand>
Yeah Exactly Thanks let me fix that

2020-11-17 01:27 UTC, closed without merging

2020-11-17 01:27 UTC, hnicolus commented
Issue fixed